const arr = [1,2,3];

arr.at(0)
arr.concat(4)
arr.copyWithin(0, 1)
arr.entries()
arr.every((v) => v)
arr.fill(0)
arr.filter((v) => v)
arr.find((v) => v)
arr.findIndex((v) => v)
arr.findLast((v) => v)
arr.findLastIndex((v) => v)
arr.flat()
arr.flatMap((v) => v)
arr.forEach((v) => v)
arr.includes(1)
arr.indexOf(0)
arr.join()
arr.keys()
arr.lastIndexOf(1)
arr.map((v) => v)
arr.pop()
arr.push()
arr.reduce((v) => v)
arr.reduceRight((v) => v)
arr.reverse()
arr.shift()
arr.slice()
arr.some((v) => v)
arr.sort()
arr.splice(1)
arr.toLocaleString()
arr.toReversed()
arr.toSorted()
arr.toSpliced()
arr.toString()
arr.unshift()
arr.values()
arr.with()
arr.length
